### ISSUE TITLE
404

### ISSUE THREAD

**Issue by FranciscoImanolSuarez** [faztcommunity/fazt-web#18]
Hola ! Puedo agregar el redireccionamiento en error 404? Si están de acuerdo tomo ese tema!

**Comment by leave20** [comment]
Toda ayuda es bienvenida , pero para tener una mejor comunicación dirigirte a la comunidad en Discord : https://discord.gg/JjcRfCB

**Comment by leave20** [comment]
Preguntar en #Cafetería por Craig
